#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
autorandr -c

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends --config "$HOME"/.config/picom/picom.conf &> /dev/null &
fi

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
hsetroot -center "$SCRIPTPATH"/background.png

if [ -x "$(command -v redshift)" ]; then
  killall redshift
  redshift -l 47:13 &
fi

#Start Polybar
export index=0
monitors=($(polybar -m | sed 's/:.*//'))
leftwm-state -q -n -t "$SCRIPTPATH"/liquid/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$HOME"/.config/polybar/polybar.config $barname &> /dev/null &

  workspacesname="workspacebar$index"
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$HOME"/.config/polybar/polybar.config $workspacesname &> /dev/null &
  let index=index+1
done


